package util;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.*;

public class DatabaseUtil {
    private static final String DB_URL = "jdbc:hsqldb:file:tourdb/tourdb;shutdown=true";
    private static final String DB_USER = "SA";
    private static final String DB_PASSWORD = "";

    private static HikariDataSource dataSource;

    static {
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");

            HikariConfig config = new HikariConfig();
            config.setJdbcUrl(DB_URL);
            config.setUsername(DB_USER);
            config.setPassword(DB_PASSWORD);

            // ==== CẤU HÌNH POOL ====
            config.setMaximumPoolSize(10);
            config.setMinimumIdle(2);
            config.setIdleTimeout(30000);
            config.setConnectionTimeout(10000);
            config.setPoolName("TourHikariPool");

            dataSource = new HikariDataSource(config);

            initDatabase();

            System.out.println("HikariCP initialized!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // DAO gọi hàm này để truy vấn DB
    public static Connection getConnection() throws SQLException {
    	return dataSource.getConnection();
    	}

    private static void initDatabase() {
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            
            // Tạo bảng users
            stmt.execute("CREATE TABLE IF NOT EXISTS users (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "username VARCHAR(50) UNIQUE NOT NULL," +
                "password VARCHAR(255) NOT NULL," +
                "fullname VARCHAR(100) NOT NULL," +
                "email VARCHAR(100) UNIQUE NOT NULL," +
                "phone VARCHAR(20)," +
                "address VARCHAR(255)," +
                "role VARCHAR(20) DEFAULT 'USER'," +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

            // Tạo bảng categories
            stmt.execute("CREATE TABLE IF NOT EXISTS categories (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR(100) NOT NULL," +
                "description VARCHAR(255))");

            // Tạo bảng tours
            stmt.execute("CREATE TABLE IF NOT EXISTS tours (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "name VARCHAR(255) NOT NULL," +
                "description CLOB," +
                "location VARCHAR(100)," +
                "duration INT," +
                "price DECIMAL(15,2)," +
                "discount DECIMAL(5,2) DEFAULT 0," +
                "image VARCHAR(255)," +
                "available_seats INT DEFAULT 0," +
                "departure_date DATE," +
                "category_id INT," +
                "vehicle VARCHAR(50)," +
                "itinerary CLOB," +
                "featured BOOLEAN DEFAULT FALSE," +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                "FOREIGN KEY (category_id) REFERENCES categories(id))");

            // Tạo bảng bookings
            stmt.execute("CREATE TABLE IF NOT EXISTS bookings (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "user_id INT NOT NULL," +
                "tour_id INT NOT NULL," +
                "booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                "departure_date DATE," +
                "num_people INT NOT NULL," +
                "total_price DECIMAL(15,2)," +
                "contact_name VARCHAR(100)," +
                "contact_phone VARCHAR(20)," +
                "contact_email VARCHAR(100)," +
                "notes CLOB," +
                "status VARCHAR(20) DEFAULT 'PENDING'," +
                "FOREIGN KEY (user_id) REFERENCES users(id)," +
                "FOREIGN KEY (tour_id) REFERENCES tours(id))");

            // Tạo bảng reviews
            stmt.execute("CREATE TABLE IF NOT EXISTS reviews (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "tour_id INT NOT NULL," +
                "user_id INT NOT NULL," +
                "rating INT CHECK (rating >= 1 AND rating <= 5)," +
                "comment CLOB," +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                "FOREIGN KEY (tour_id) REFERENCES tours(id)," +
                "FOREIGN KEY (user_id) REFERENCES users(id))");

            // Tạo bảng payments
            stmt.execute("CREATE TABLE IF NOT EXISTS payments (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "booking_id INT NOT NULL," +
                "payment_method VARCHAR(50)," +
                "payment_status VARCHAR(20) DEFAULT 'PENDING'," +
                "amount DECIMAL(15,2)," +
                "payment_date TIMESTAMP," +
                "transaction_id VARCHAR(100)," +
                "FOREIGN KEY (booking_id) REFERENCES bookings(id))");

            // Insert dữ liệu mẫu
            insertSampleData(conn);
            
            System.out.println("Database initialized successfully!");
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private static void insertSampleData(Connection conn) throws SQLException {
        // Kiểm tra xem đã có dữ liệu chưa
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM users")) {
            rs.next();
            if (rs.getInt(1) > 0) return;
        }

        // Insert admin user
        try (PreparedStatement ps = conn.prepareStatement(
            "INSERT INTO users (username, password, fullname, email, phone, role) VALUES (?, ?, ?, ?, ?, ?)")) {
            ps.setString(1, "admin");
            ps.setString(2, "admin123"); // Trong thực tế nên hash password
            ps.setString(3, "Quản Trị Viên");
            ps.setString(4, "admin@tourbook.com");
            ps.setString(5, "0901234567");
            ps.setString(6, "ADMIN");
            ps.executeUpdate();
        }

        // Insert user mẫu
        try (PreparedStatement ps = conn.prepareStatement(
            "INSERT INTO users (username, password, fullname, email, phone) VALUES (?, ?, ?, ?, ?)")) {
            ps.setString(1, "user1");
            ps.setString(2, "user123");
            ps.setString(3, "Nguyễn Văn A");
            ps.setString(4, "user1@gmail.com");
            ps.setString(5, "0912345678");
            ps.executeUpdate();
        }

        // Insert categories
        String[] categories = {
            "Tour Trong Nước", "Tour Quốc Tế", "Tour Nghỉ Dưỡng", 
            "Tour Mạo Hiểm", "Tour Khám Phá Văn Hóa"
        };
        for (String cat : categories) {
            try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO categories (name) VALUES (?)")) {
                ps.setString(1, cat);
                ps.executeUpdate();
            }
        }

        // Insert tours mẫu
        insertTour(conn, "Du lịch Đà Lạt 3N2Đ", "Khám phá thành phố ngàn hoa với khí hậu mát mẻ quanh năm", 
            "Đà Lạt", 3, 3500000, 10, "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800", 30, "2025-01-15", 1, "Xe khách", 
            "Ngày 1: TP.HCM - Đà Lạt\nNgày 2: Tham quan Thác Datanla, Dinh Bảo Đại\nNgày 3: Hồ Tuyền Lâm - Về", true);

        insertTour(conn, "Tour Phú Quốc 4N3Đ", "Thiên đường biển đảo với bãi cát trắng và nước biển trong xanh", 
            "Phú Quốc", 4, 5500000, 15, "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800", 25, "2025-01-20", 3, "Máy bay", 
            "Ngày 1: HN/SGN - Phú Quốc\nNgày 2-3: Tham quan các bãi biển, Vinpearl Safari\nNgày 4: Chợ đêm - Về", true);

        insertTour(conn, "Du lịch Sapa 3N2Đ", "Khám phá vùng cao Tây Bắc với ruộng bậc thang tuyệt đẹp", 
            "Sapa", 3, 4200000, 5, "https://images.unsplash.com/photo-1528127269322-539801943592?w=800", 20, "2025-02-01", 1, "Xe giường nằm", 
            "Ngày 1: HN - Sapa\nNgày 2: Fansipan, bản Cát Cát\nNgày 3: Thị trấn Sapa - Về", true);

        insertTour(conn, "Tour Thái Lan Bangkok-Pattaya 5N4Đ", "Khám phá xứ sở chùa vàng với lịch trình hấp dẫn", 
            "Bangkok, Thái Lan", 5, 8900000, 20, "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800", 15, "2025-01-25", 2, "Máy bay", 
            "Ngày 1-2: Bangkok\nNgày 3-4: Pattaya\nNgày 5: Mua sắm - Về", false);

        insertTour(conn, "Tour Nhật Bản Tokyo-Osaka 6N5Đ", "Trải nghiệm xứ sở hoa anh đào với văn hóa độc đáo", 
            "Tokyo, Osaka", 6, 25000000, 10, "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800", 10, "2025-03-01", 2, "Máy bay", 
            "Ngày 1-3: Tokyo\nNgày 4-5: Osaka\nNgày 6: Về", false);

        insertTour(conn, "Tour Trekking Tà Năng - Phan Dũng", "Chinh phục cung đường trekking đẹp nhất Việt Nam", 
            "Đức Trọng, Lâm Đồng", 2, 1500000, 0, "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800", 12, "2025-01-18", 4, "Xe khách", 
            "Ngày 1: Di chuyển và bắt đầu hành trình\nNgày 2: Hoàn thành cung đường - Về", false);
    }

    private static void insertTour(Connection conn, String name, String desc, String loc, 
        int duration, double price, double discount, String img, int seats, String depDate, 
        int catId, String vehicle, String itinerary, boolean featured) throws SQLException {
        
        try (PreparedStatement ps = conn.prepareStatement(
            "INSERT INTO tours (name, description, location, duration, price, discount, image, " +
            "available_seats, departure_date, category_id, vehicle, itinerary, featured) " +
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")) {
            ps.setString(1, name);
            ps.setString(2, desc);
            ps.setString(3, loc);
            ps.setInt(4, duration);
            ps.setDouble(5, price);
            ps.setDouble(6, discount);
            ps.setString(7, img);
            ps.setInt(8, seats);
            ps.setDate(9, Date.valueOf(depDate));
            ps.setInt(10, catId);
            ps.setString(11, vehicle);
            ps.setString(12, itinerary);
            ps.setBoolean(13, featured);
            ps.executeUpdate();
        }
    }
}